services:
  uptime-kuma:
    image: ${UPTIME_KUMA_IMAGE:-ghcr.io/louislam/uptime-kuma:main}
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    ports:
      # <Host Port>:<Container Port>
      - "3001:3001"
